### ISSUE TITLE
Vote on the framework that we are going to use

### ISSUE THREAD

**Issue by papac** [liberty-space/liberty-api#2]
❤️ For Bow Framework
😄 For Laravel
🎉 For Nodejs (Expressjs or NestJs)
👍 For Vanilla (PHP or Nodejs)

**Comment by papac** [comment]
:heart:

**Comment by Sgourebi** [comment]
Add symfony plz

**Comment by papac** [comment]
@Sgourebi is cool also !

**Comment by arnoldkouya** [comment]
😄

**Comment by papac** [comment]
@arnoldkouya Laravel ? It’s opportunity to learn Bow Framework

**Comment by arnoldkouya** [comment]
@papac yes #bow is good, you must to setup the codebase and we can follow you.
